### ISSUE TITLE
Could the Multisite documentation page/s be clarified?

### ISSUE THREAD

**Issue by normancates** [civicrm/civicrm-sysadmin-guide#105]
https://docs.civicrm.org/sysadmin/en/latest/install/multi-site/

It's extremely unclear if the first section also applies to Wordpress. 

It's also uncelar in any of this if these instructions will create a segregated CiviCRM install. 

ie. with different data per subsite. 

I personally want to share all the data between sites.

There's other places that say that it's possible to separate the multisites completely. But this page doesn't talk about either of those options.

It would be really useful to put notes in about what's changed between civiCRM versions. Because it appears that in 4.6 and prior the civicrm.settings.php file lives in one place, but in later versions it lives somewhere else.

It also appears to have changed how multisites work, because in this version (5.2.2) the extra civiCRM sites directories don't seem to be being created as they were in 4.6.

Or I'm doing something wrong. In any case, getting the documentation better would be great.

Thanks,
Norman

**Comment by eileenmcnaughton** [comment]
Note I believe this was an attempt at that https://github.com/civicrm/civicrm-sysadmin-guide/pull/104/files (I just merged it)

**Comment by normancates** [comment]
Ah. that does add some interesting stuff.

However, the path in the CIVICRM_SETTINGS_PATH is unclear. Is that a URL or a server path.

It's unclear.

I'm assuming it's a server path...

However, there are still massive problems. I can get the sub sites, but I get the infamous Network error:

Network Error
Unable to reach the server. Please refresh this page in your browser and try again.

And in Chrome I I seeing these Javascript errors in the console.

(anonymous) @ query-monitor.js?ver=1529466446:300
admin.php?page=CiviCRM:1 Failed to load https://<website URL>/wp-admin/admin.php?page=CiviCRM&q=civicrm/dashlet/getting-started&reset=1&snippet=json: Redirect from 'https://<website URL>/wp-admin/admin.php?page=CiviCRM&q=civicrm/dashlet/getting-started&reset=1&snippet=json' to 'https://<website URL>/wp-login.php?redirect_to=https%3A%2F%2F<website URL>%2Fwp-admin%2Fadmin.php%3Fpage%3DCiviCRM%26q%3Dcivicrm%2Fdashlet%2Fgetting-started%26reset%3D1%26snippet%3Djson&reauth=1' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://crew.<website URL>' is therefore not allowed access.

---------------------

I don't know what's changed, but this is a pretty serious problem. Assuming I';m not the only one...

Norm

**Comment by eileenmcnaughton** [comment]
hmm so redirecting to 

https:///wp-login.php?redirect_to=https%3A%2F%2F%2Fwp-admin%2Fadmin.php%3Fpage%3DCiviCRM%26q%3Dcivicrm%2Fdashlet%2Fgetting-started%26reset%3D1%26snippet%3Djson&reauth=1

- looks like it's a login redirect - but you are already logged in. Your urls don't have the domain part masked - but they don't include 'variants?' -ie 

http://www.example.com
http://example.com
https://www.example.com
https://example.com

**Comment by eileenmcnaughton** [comment]
@normancates so each domain (including subdomains) has a domain id which determines which settings are loaded - including navigation & urls etc. If one is not defined it defaults to 1.

I'm not up with all your config - I have 2 wordpress sites sharing a CIviCRM instance but they don't have a shared codebase, they are simply on the same server. 

On one site I have the line
```
define(''CIVICRM_DOMAIN_ID', 1);
```
and on the other 
```
define(''CIVICRM_DOMAIN_ID', 2);
```

This is the function that retrieves the id.
```
  /**
   * One function to get domain ID.
   *
   * @param int $domainID
   * @param bool $reset
   *
   * @return int|null
   */
  public static function domainID($domainID = NULL, $reset = FALSE) {
    static $domain;
    if ($domainID) {
      $domain = $domainID;
    }
    if ($reset || empty($domain)) {
      $domain = defined('CIVICRM_DOMAIN_ID') ? CIVICRM_DOMAIN_ID : 1;
    }

    return $domain;
  }

```

 civicrm.settings.php file defines the domain id - so you would have

dev.domain.nz's config file:

**Comment by normancates** [comment]
this is the domain and URL information that I currently have in my civicrm.settings.php file

=================
if(function_exists('is_multisite') && function_exists('home_url')) {
  $url = home_url();
}
else {
  $protocol = strstr('HTTPS', $_SERVER['SERVER_PROTOCOL']) ? 'https://' : 'http://';
  $url = $protocol . $_SERVER['SERVER_NAME'];
}


/**
 * CiviCRM Configuration File
 */
  //this if statement covers running from CLI (e.g. bin/csv/import.php)
  if(empty($_SERVER['SERVER_NAME'])) {
    define( 'CIVICRM_DOMAIN_ID', 1 );
  }


if (!defined('CIVICRM_DOMAIN_ID')) {
  define( 'CIVICRM_DOMAIN_ID', 1);
} 

 define( 'CIVICRM_UF_BASEURL', $url );

=================

My intent is to just use the Civi database as is in each sub site.

As far as I can tell, this SHOULD do it.

Because I'm getting the URL based on the site I'm in, and I'm using the one domain for CiviCRM...

So there will be no separation of the information. In this case, that's what I want.

I am still getting a Network Error on the main home page, but otherwise, everything seems to be working...

**Comment by eileenmcnaughton** [comment]
Maybe check civicrm_settings table to see if any the settings are non-relative (as relates to paths or urls)?

**Comment by normancates** [comment]
Yeah, at the moment I'm just trying to get the page at:

site.dev.domain.nz/wp-admin/admin.php?page=CiviCRM

to come up the same as 

dev.domain.nz/wp-admin/admin.php?page=CiviCRM

BTW, thanks for your help so far. It's much appreciated. 

These problems are so bizarre!

**Comment by normancates** [comment]
Yeah, this is 5.3 at the moment. Since my dev data got blown away by accident, I thought I'd just take the opportunity to go to the latest.

**Comment by eileenmcnaughton** [comment]
ok - I'm on chat now - we should discuss this there - WP channel

**Comment by MegaphoneJon** [comment]
I just submitted PR #113 which should clarify the opening sections of the multisite documentation, including removing some Drupal-specific language that should be CMS-agnostic.

I'm going to close this issue, but @normancates if you feel the changes in #113 aren't sufficient, please give feedback!
