### ISSUE TITLE
Create Backdrop upgrade page

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-sysadmin-guide#11]
We have a page on [Installing CiviCRM in backdrop](https://docs.civicrm.org/sysadmin/en/latest/install/backdrop/) (recently migrated from the wiki), but we don't have a page on *upgrading* CiviCRM after it's installed within Backdrop. For comparison, we have upgrade pages for CiviCRM [in Drupal](https://docs.civicrm.org/sysadmin/en/latest/upgrade/drupal7/), [in Wordpress](https://docs.civicrm.org/sysadmin/en/latest/upgrade/wordpress/), and [in Joomla](https://docs.civicrm.org/sysadmin/en/latest/upgrade/joomla/). I think that if we are to claim we support Backdrop, we need to create a page on upgrading CiviCRM within Backdrop.

**Comment by seanmadsen** [comment]
Tagging @MegaphoneJon and @herbdool because each of you created wiki pages on installing Backdrop (independently of one another, [as](https://wiki.civicrm.org/confluence/display//CRMDOC/Installing+CiviCRM+for+Backdrop) it [seems](https://wiki.civicrm.org/confluence/display//CRMDOC/Installing+CiviCRM+for+Backdrop+CMS)!)

**Comment by herbdool** [comment]
@seanmadsen @MegaphoneJon and I had agreed that the version I created was the canonical version. The other can be archived.

**Comment by seanmadsen** [comment]
Resolved with #51
