### ISSUE TITLE
Add in a Backdrop integration section

### ISSUE THREAD

**Issue by laryn** [civicrm/civicrm-sysadmin-guide#149]
We have [Backdrop installation](https://github.com/civicrm/civicrm-sysadmin-guide/blob/master/docs/install/backdrop.md) and [upgrade](https://github.com/civicrm/civicrm-sysadmin-guide/blob/master/docs/upgrade/backdrop.md) sections but no main integration info. 

PR coming with a first pass at cloning and tweaking the relevant Drupal integration pages.

**Comment by MegaphoneJon** [comment]
Given the similarities, I'm wondering if it makes sense to simply make a Drupal/Backdrop integration page instead?  And indicate in section headers "[Drupal]" or "[Drupal/Backdrop]"?

**Comment by laryn** [comment]
Sounds good, thanks.

**Comment by MikeyMJCO** [comment]
Resolved with #150
