### ISSUE TITLE
Improve docs on iATS

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-sysadmin-guide#15]
In the Sysadmin Guide we now have the following doc page on iATS, as migrated from the wiki:

https://docs.civicrm.org/sysadmin/en/latest/setup/payment-processors/iats

I *think* this page should be improved in the following ways: 

* Make it clearer to readers that the official iATS docs are found elsewhere by doing the following:
    * Link to the official iATS docs [here](https://github.com/iATSPayments/com.iatspayments.civicrm/blob/master/README.md):  (Yes, the page mentions the README, but a link would be great.)
    * Remove content in the Sysadmin Guide related to configuration (because that content should be in the official iATS docs)
* (If appropriate) remove the link to the old iATS extension.

Ping @KarinG @adixon

**Comment by adixon** [comment]
Thanks sean, PR submitted:  https://github.com/civicrm/civicrm-sysadmin-guide/pull/25

**Comment by seanmadsen** [comment]
Resolved with #25
