### ISSUE TITLE
unable to install with drupal 7

### ISSUE THREAD

**Issue by flik** [civicrm/civicrm-sysadmin-guide#153]
Here is error detail:

    Warning: count(): Parameter must be an array or an object that implements Countable in InstallRequirements->hasErrors() (line 1403 of /xxxx/drupal70/sites/all/modules/civicrm/install/index.php).
    Deprecated function: The each() function is deprecated. This message will be suppressed on further calls in _drupal_shutdown_function() (line 3076 of /vagrant/drupal70/includes/bootstrap.inc).
    Warning: count(): Parameter must be an array or an object that implements Countable in InstallRequirements->hasErrors() (line 1403 of /xxxx/drupal70/sites/all/modules/civicrm/install/index.php).
    Warning: count(): Parameter must be an array or an object that implements Countable in InstallRequirements->hasWarnings() (line 1410 of /xxxx/drupal70/sites/all/modules/civicrm/install/index.php).
    Warning: count(): Parameter must be an array or an object that implements Countable in InstallRequirements->hasErrors() (line 1403 of /xxxxx/drupal70/sites/all/modules/civicrm/install/index.php).
    Warning: count(): Parameter must be an array or an object that implements Countable in InstallRequirements->hasErrors() (line 1403 of /xxxx/drupal70/sites/all/modules/civicrm/install/index.php).
    Deprecated function: The each() function is deprecated. This message will be suppressed on further calls in _drupal_shutdown_function() (line 3076 of /xxxx/drupal70/includes/bootstrap.inc).
    Warning: count(): Parameter must be an array or an object that implements Countable in InstallRequirements->hasErrors() (line 1403 of /xxxx/drupal70/sites/all/modules/civicrm/install/index.php).
    Warning: count(): Parameter must be an array or an object that implements Countable in InstallRequirements->hasErrors() (line 1403 of /xxxx/drupal70/sites/all/modules/civicrm/install/index.php).
    Warning: count(): Parameter must be an array or an object that implements Countable in InstallRequirements->hasErrors() (line 1403 of /xxxx/drupal70/sites/all/modules/civicrm/install/index.php).
    Warning: mkdir(): Permission denied in civicrm_setup() (line 61 of /xxxx/drupal70/sites/all/modules/civicrm/install/civicrm.php).
    PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'civicrm_handler_field_custom_file-class' for key 'PRIMARY': INSERT INTO {registry} (name, type, filename, module, weight) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4); Array ( [:db_insert_placeholder_0] => civicrm_handler_field_custom_file [:db_insert_placeholder_1] => class [:db_insert_placeholder_2] => sites/all/modules/civicrm/drupal/modules/views/civicrm/civicrm_handler_field_custom_file.inc [:db_insert_placeholder_3] => civicrm [:db_insert_placeholder_4] => 0 ) in _registry_parse_file() (line 179 of /xxxx/drupal70/includes/registry.inc).

**Comment by flik** [comment]
Error: Call to a member function url() on null in CRM_Utils_System::url() (line 294 of /xxxx/drupal70/sites/all/modules/civicrm/CRM/Utils/System.php).

**Comment by flik** [comment]
I am using php 7.3

**Comment by MegaphoneJon** [comment]
@flik Could you please post this on https://civicrm.stackexchange.com instead?  Also, be sure to include your CMS version and the version of CiviCRM you're using.
