### ISSUE TITLE
page not found 

### ISSUE THREAD

**Issue by ashfaqconvo** [civicrm/civicrm-sysadmin-guide#154]
Hi,

When I click on requirement page from civicrm-sysadmin-guide/docs/install/drupal7.md

Just click on requirements link you will receive page not found.

**Comment by flik** [comment]
I have the same issue...

**Comment by mlutfy** [comment]
Hi,

Could you provide the URL in question?

I tried here: https://docs.civicrm.org/sysadmin/en/latest/install/drupal7/

It has a requirements link to here: https://docs.civicrm.org/sysadmin/en/latest/requirements/

but that one seems OK?

**Comment by flik** [comment]
Here is link: https://github.com/civicrm/civicrm-sysadmin-guide/blob/master/requirements.md

here is screen short: [https://photoland.io/i/2P5RrG](https://photoland.io/i/2P5RrG)

**Comment by mlutfy** [comment]
The official URL is: https://docs.civicrm.org/sysadmin/en/latest/

This Github repository is for the redaction of the guide.
