### ISSUE TITLE
What is keyboard_arrow_down?

### ISSUE THREAD

**Issue by zhaofeng-shu33** [civicrm/civicrm-sysadmin-guide#162]
I guess this is a bug.
![image](https://user-images.githubusercontent.com/23316477/55478734-f9ce5e80-564e-11e9-800e-d1e7082a3d96.png)
It happens on Chrome (OS: windows)

**Comment by mattwire** [comment]
Thankyou for reporting.  I don't see this here: 
![image](https://user-images.githubusercontent.com/2052161/55496393-d4cdf180-5636-11e9-87a0-65d5540f9861.png)

Are there any errors in your browser console?  Or could it be the language of your browser?

**Comment by zhaofeng-shu33** [comment]
After using developer console, I found some static access from fonts.googleapis.com failed to load. This is not due to website itself. I will try to fix the network error by myself. Thank you very much!
