### ISSUE TITLE
Conflicting information regarding PayPal Instant Payment Notification setup

### ISSUE THREAD

**Issue by mikantchap** [civicrm/civicrm-sysadmin-guide#166]
https://docs.civicrm.org/sysadmin/en/latest/setup/payment-processors/paypal-standard/

states you should enter your base site URL whereas

https://docs.civicrm.org/sysadmin/en/latest/setup/payment-processors/recurring/#IPN%20notify%20URL

states you should enter eg

civicrm/payment/ipn/3

(presumably prefixed with the base URL)

https://chat.civicrm.org/civicrm/pl/rmtxenf9w7y33k5djny19f5fbe

**Comment by mattwire** [comment]
@mikantchap From what I understand, specifically to paypal standard, it doesn't care what you enter in their dashboard as it will always use the URL passed in when a payment is submitted.  So I don't think there is a conflict here?

**Comment by mikantchap** [comment]
Hi Matt

The 2 pieces of documentation are different - that's confusing! Something has to be entered into the PayPal backend (I was advised that it was eg "civicrm/payment/ipn/3" - see the chat link above) so can we unify the docs to whatever has to be put into PayPal? I presume you can't leave it blank and it will still work.

**Comment by mikantchap** [comment]
I can now report that a client's recurring paypal IPNs starting working after they swapped to "civicrm/payment/ipn/3" rather than just the base URL.

**Comment by JoeMurray** [comment]
How does https://github.com/civicrm/civicrm-sysadmin-guide/pull/169/files look as a change to the documentation?

**Comment by JoeMurray** [comment]
Closing as @mattwire committed PR that reflected @mikantchap's concern.
