### ISSUE TITLE
Resolve duplicate content on Drupal views

### ISSUE THREAD

**Issue by seancolsen** [civicrm/civicrm-sysadmin-guide#17]
These two sections have very similar content

* https://docs.civicrm.org/sysadmin/en/latest/integration/drupal/#drupal-views
* https://docs.civicrm.org/sysadmin/en/latest/integration/drupal/views/

Resolve by:

1. Choosing one place for the content to live (I don't have an opinion about this)
1. Merging the content into one body of text that preserves concepts from both sources
1. Provide links that point readers to the new content from wherever it was removed

**Comment by MegaphoneJon** [comment]
Closed by #122.
