### ISSUE TITLE
New page for describing how to custom paths

### ISSUE THREAD

**Issue by herbdool** [civicrm/civicrm-sysadmin-guide#179]
With the merging of https://github.com/civicrm/civicrm-core/pull/14718 we will soon have better ways to set file paths. I suggest creating a page with examples of how to do that and why some people might want to do so.

**Comment by herbdool** [comment]
I believe this comment https://github.com/civicrm/civicrm-core/pull/14718#issuecomment-511689465 will help in drafting a page for the guide.

**Comment by MikeyMJCO** [comment]
Ah - we've already documented this recently (ish!)

https://docs.civicrm.org/sysadmin/en/latest/customize/paths/

If that meets the requirements above - we can close this - otherwise I'll label it appropriately so it needs work :-)

**Comment by herbdool** [comment]
Yeah, I was trying to refresh my memory and followed some threads and came to that same page.

I think that page fits the bill. So I'm happy to close this. Thanks @MikeyMJCO!

**Comment by herbdool** [comment]
I think this is a good example of how the autocloser bot works well. It made me figure out why this issue was still open.
