### ISSUE TITLE
Clean up CiviMail docs

### ISSUE THREAD

**Issue by seancolsen** [civicrm/civicrm-sysadmin-guide#19]
Relevant pages:

* https://docs.civicrm.org/sysadmin/en/latest/setup/civimail/
* https://docs.civicrm.org/sysadmin/en/latest/setup/civimail/outbound/
* https://docs.civicrm.org/sysadmin/en/latest/setup/civimail/inbound/

I brought stuff into this chapter from (a) the User Guide and (b) a bunch of different pages on the wiki. Now it's kind of a mess and has some duplicate content. Needs merging, cleaning, and some re-organizing.

**Comment by michaelmcandrew** [comment]
great stuff, sean - keep it up! :smile:
