### ISSUE TITLE
Introduce documentation about theming

### ISSUE THREAD

**Issue by totten** [civicrm/civicrm-sysadmin-guide#191]
Civi 5.16 introduced a formal theme setting, and the developer docs include a description of the [technical mechanism](https://docs.civicrm.org/dev/en/latest/framework/theme/).

We should expand Sysadmin docs to talk more about the process/benefits/considerations of installing a theme extension like Shoreditch/Haystacktheme.

This may be a good topic to discuss in Barcelona.

**Comment by MikeyMJCO** [comment]
Handled by #192 - closing.
