### ISSUE TITLE
What is the minimum CiviCRM version that this guide should support?

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-sysadmin-guide#2]
Some of the installation and upgrade docs in the wiki go *waay* back to super old versions. How far back should we go with this guide? This is particularly relevant for *upgrades* where a user might still be on an old version and require instructions specific to that version for how to upgrade *off* of it.

For example, the page on [upgrading Drupal 7 sites for CiviCRM 4.7](https://wiki.civicrm.org/confluence/display/CRMDOC/Upgrading+CiviCRM+for+Drupal+7) says:

> Upgrading from a version prior to 2.2? First upgrade to 2.2 [using these instructions](https://wiki.civicrm.org/confluence/display/CRMDOC22/Upgrade+Drupal+Sites+to+2.2).

So a specific question here is: *do we want to migrate this page on [upgrading Drupal sites to 2.2](https://wiki.civicrm.org/confluence/display/CRMDOC22/Upgrade+Drupal+Sites+to+2.2)?* ... I say no.

The [stats](https://stats.civicrm.org/?tab=sites) only go back to 4.2.

I propose that the scope of this guide be limited to 4.0 and later. Curious to hear feedback from others on this proposal.

**Comment by nganivet** [comment]
+1  If anyone is still on 3.x or earlier at this point in time they are 
most probably never going to upgrade, or will need (a lot of) 
professional help if they ever decide to.

------ Original Message ------

**Comment by colemanw** [comment]
Technical note - the latest version of CiviCRM supports upgrading from 4.1+

**Comment by JoeMurray** [comment]
Let's archive the old stuff and make it harder to find by searches, but available. Looking at https://stats.civicrm.org/?tab=sites, and taking into account @colemanw 's comment, let's only support 4.1+, and only insofar as it is standard procedure for all versions.

**Comment by seanmadsen** [comment]
I'm all for supporting 4.1+, and will plan on that, given the above comments.

**Comment by colemanw** [comment]
Are you talking about documentation for *using* 4.1? Or *upgrading from* 4.1 to a supported version?
IMHO our new documentation should only cover using 4.7 (and maybe 4.6 but I'm not sure that's worth your time).
And AFAIK there is no special documentation for upgrading from particular versions, it's all just "install the new code & run the upgrader" regardless of prior version (as long as that prior version is 4.1+)

**Comment by seanmadsen** [comment]
@colemanw Documentation for *using* CiviCRM, will still be covered by the User Guide, which only focuses on 4.6 and 4.7. 

My plan, as covered in #3 is as follows: 

> * Use branches `4.6` and `master` to represent the CiviCRM *target* version. In the case of *installing* this is straightforward. In the case of *upgrading* the reader would use the guide for the version they're upgrading *to* (not from). In rare cases where we might need to provide different documentation for point releases (e.g. 4.7.21 etc) then we would use [admonitions](https://docs.civicrm.org/dev/en/latest/documentation/markdown/#admonitions).
> 
> * For documentation that differs by CMS, use different pages within the guide.
> 
> * When CMS versions are substantially different (i.e Drupal), treat different versions (6, 7, 8) effectively as different CMS platforms. So, use different installation pages for "Drupal 7" and "Drupal 8".

The main purpose of *this* ticket was to agree that we should not bring over the super old docs on upgrading to v2.2. I framed the ticket somewhat more broadly because I didn't know if there would be other versions which would also require specific instructions to *upgrade from*.

Hearing that upgrading from 4.1 onwards does not require version-specific instructions is useful information and simplifies this decision.

So I think that, in both branches of the Sysadmin Guide (`4.6` and `master`), the upgrade instructions will tell the user they must begin with CiviCRM 4.1 or later.

**Comment by seanmadsen** [comment]
In the spirit of making progress through making decisions, I'm closing this ticket now and will be moving forward with the plan listed in my previous comment.

If anyone has further comments, please feel free to make them here, even though this ticket is closed. I'm still open to tweaking the plan.
