### ISSUE TITLE
Clean up Scheduled Jobs docs

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-sysadmin-guide#20]
This page: https://docs.civicrm.org/sysadmin/en/latest/setup/jobs/

I brought stuff into this page from (a) the User Guide and (b) two different pages on the wiki. Now it's kind of a mess and has some duplicate content. Needs merging, cleaning, and some re-organizing.

Related: https://lab.civicrm.org/documentation/docs/issues/4

**Comment by joannechester** [comment]
Are you removing the documentation from the user guide when you bring it across to the sysadmin guide?
As a admin user I think it is important that info on creating scheduled jobs, particularly emailing of reports, is available in the user guide.

**Comment by seanmadsen** [comment]
Yeah, I moved the whole page on scheduled jobs over from the User Guide to the Sysadmin Guide because part of the page contained technical details on setting up cron jobs. Now, as part of this re-organization, I definitely need to move some of that content *back* to the User Guide. I'll get to this soon. Thanks for the reminder @joannechester

**Comment by seanmadsen** [comment]
Also related: https://github.com/civicrm/civicrm-user-guide/pull/148
