### ISSUE TITLE
Clean up hyperlinks to the wiki

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-sysadmin-guide#21]
This guide has lots of hyperlinks which point to the wiki. Many of these links should actually point to this guide, or other guides. 

I think we should do this with an automated process, because designing one would be useful for other guides (and future projects as well). 

1. Use a regex to extract external hyperlinks from the markdown (*all* external hyperlinks, not just wiki ones)
1. For each hyperlink, see if the URL responds with an HTTP redirect
1. If so, modify markdown with the new redirect.

At this point I think the work of creating a script which performs the above tasks will be faster than the work of manually fixing all those URLs.

**Comment by michaelmcandrew** [comment]
Hey Sean,
Not sure if you have thought of this but there are a lot of links in CiviCRM's UI as well that will need updating at some point. If you were able to generalise the script to cater for that use case, or just keep that in mind so it could be easily extended, it might be worth it.

**Comment by seanmadsen** [comment]
Great idea @michaelmcandrew !! I'll keep that in mind.

**Comment by seanmadsen** [comment]
Well, I *wanted* to do this with a script, but there ended up being too many edge cases to make automation worthwhile. My approach was pretty manual, with much help from `grep`. Sorry @michaelmcandrew
