### ISSUE TITLE
Clarify that clean URLs in WordPress are for front end pages

### ISSUE THREAD

**Issue by michaelmcandrew** [civicrm/civicrm-sysadmin-guide#221]
https://docs.civicrm.org/sysadmin/en/latest/install/wordpress/#enabling-cleaner-urls-for-wordpress  says

> "Starting in Version 5.13.x CiviCRM now can support "Clean URLs" for WordPress"

It is probably worth clarifying that this is for front end pages. We could change it to

> "Starting in Version 5.13.x CiviCRM now can support "Clean URLs" for WordPress for front end pages"

**Comment by MikeyMJCO** [comment]
Yes - I'd agree that's a good change!

**Comment by MikeyMJCO** [comment]
PR up for review - tweaked the wording slightly.
