### ISSUE TITLE
Wrong Menus, Upgrading CiviCRM for Backdrop CMS

### ISSUE THREAD

**Issue by Michael-IDA** [civicrm/civicrm-sysadmin-guide#265]
Post Edit Note:
Finally figured out why everything about the Backdrop menus are wrong.  Someone copy/pasted the Breadcrumb, which is not the menu structure (and no one uses the breadcrumb in Drupal/Backdrop as UI pathing). The CiviCRM menu wrongness I'd guess is just normal update creep.  Fixed what I could, it’s not completely in order as I added some obvious sections afterwards.

# # #

Errors in:  https://docs.civicrm.org/sysadmin/en/latest/upgrade/backdrop/

Section: Disable all CiviCRM integration modules
Section: Re-enable compatible CiviCRM integration modules

>- In Backdrop, go to Administration » Functionality

-should be something like-

>+ Backdrop Menu:  Functionality » List Modules
>+ Path:  /admin/modules

Section: Review and update Backdrop permissions settings
>- Administer CiviCRM » Users and Permissions » Permissions (Access Control) » Backdrop Access Control:

-should be something like-

>+ CiviCRM Menu: Administer » Users and Permissions » Permissions (Access Control)
>+ Path:  civicrm/admin/access?reset=1
>+ Click:  Backdrop Access Control

Section: Clear the views cache
>+ Backdrop Menu:  Structure » Views » Settings » Advanced
>+ Path:  admin/structure/views/settings/advanced
>+ Click:  CLEAR VIEWS' CACHE

Section: Restore CiviCRM as the Backdrop homepage if appropriate
>+ Backdrop Menu:  Configuration » System » Site information
>+ Path:  admin/config/system/site-information
>+ Block:  HOME PAGE, Default home page

Section: Put the site online
>+ Backdrop Menu:  Configuration » Development » Maintenance mode
>+ Path:  admin/config/development/maintenance
>+ UnCheck:   Put site into maintenance mode 

Section: Take the site offline
>+ Backdrop Menu:  Configuration » Development » Maintenance mode
>+ Path:  admin/config/development/maintenance
>+ Check:   Put site into maintenance mode 

# # #

Edit:
The whole doc could really use some clarity on which menu is being referred to when.  Also adding the path would save people an enormous amount of time.  Especially since only new to CiviCRM people will really read this and they'll have little knowledge on how to even show both the Backdrop and CiviCRM admin menus at the same time.

PS:  Why aren't these docs in a Wiki so they can be edited?  I would have done the whole thing...

**Comment by MikeyMJCO** [comment]
They are editable via this git repo where they live as Markdown files. Please submit any changes as a PR.

**Comment by MikeyMJCO** [comment]
See this docs page: https://docs.civicrm.org/user/en/latest/the-civicrm-community/contributing-to-this-manual/ for info on how to edit the docs.

**Comment by Michael-IDA** [comment]
You need to fork this repository to propose changes.

Sorry, you’re not able to edit this repository directly—you need to fork it and propose your changes from there instead.

#

You want people to learn Git to edit a doc?  Well, that'd be one reason they aren't up to date...

Seriously, if you make it a total pita, then people aren't going to help.

I tried.

Best Regards,
Michael

**Comment by MikeyMJCO** [comment]
Thanks for reporting the issue.

The attitude however you could stand to leave elsewhere.
