### ISSUE TITLE
How should we use branches within this repository?

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-sysadmin-guide#3]
The content in this guide is tricky because it has several dimensions. For example:

* CMS
* CMS *version*
* CiviCRM version
* And sometimes CiviCRM version is complicated... when we're talking about upgrading CiviCRM, the user is potentially dealing with two different major versions

I'm unsure how to organize all this, I'd like input from others.

The User Guide, by comparison, uses git branches to store different docs for 4.6 vs 4.7. We can use branches for the Sysadmin Guide too, but how do we want to use them?

Here is my proposal:

* Use branches `4.6` and `master` to represent the CiviCRM *target* version. In the case of *installing* this is straightforward. In the case of *upgrading* the reader would use the guide for the version they're upgrading *to* (not from). In rare cases where we might need to provide different documentation for point releases (e.g. 4.7.21 etc) then we would use [admonitions](https://docs.civicrm.org/dev/en/latest/documentation/markdown/#admonitions).

* For documentation that differs by CMS, use different pages within the guide.

* When CMS versions are substantially different (i.e Drupal), treat different versions (6, 7, 8) effectively as different CMS platforms. So, use different installation pages for "Drupal 7" and "Drupal 8".

**Comment by totten** [comment]
Agree on all those points.

**Comment by JoeMurray** [comment]
Agree on all points.

**Comment by seanmadsen** [comment]
In the spirit of making progress through making decisions, I'm closing this ticket now and will be moving forward with the plan listed at the beginning of this ticket. 

If anyone has further comments, please feel free to make them here, even though this ticket is closed. I'm still open to tweaking the plan.
