### ISSUE TITLE
Migrate SE content on choosing a CiviCRM version

### ISSUE THREAD

**Issue by seancolsen** [civicrm/civicrm-sysadmin-guide#34]
Great content here with lots of up-votes: 

https://civicrm.stackexchange.com/questions/35/what-is-the-civicrm-lts-version-and-should-i-use-it-or-the-latest-stable-releas

I think it'd be good to make a new page in the Sysadmin Guide called "Choosing a CiviCRM version". This would live in the "Planning your site" chapter, before "Choosing a CMS". We could mostly just copy Joe's answer, but we'd need to write a brief intro to provide some context.

**Comment by MikeyMJCO** [comment]
Closing - no longer relevant given the move to the ESR nomenclature/model.
