### ISSUE TITLE
Migrate SE content on filesystem permissions

### ISSUE THREAD

**Issue by seancolsen** [civicrm/civicrm-sysadmin-guide#36]
Some good content here: 

https://civicrm.stackexchange.com/questions/168/are-there-recommended-directory-ownership-and-permission-settings-for-civicrm-fi

Could be added here: 

https://docs.civicrm.org/sysadmin/en/latest/setup/security/#filesystem-permissions

**Comment by totten** [comment]
There is some good content there. Something related is the breakdown of permission expectations *underneath* `sites/default/files/civicrm` (etal). I'm not sure if this has everything, but the table gives the gist of it:

https://civicrm.org/advisory/civi-sa-2014-001-risk-information-disclosure

(Ex: in recent releases, we had problem-reports about deployments where the `imageUploadDir` / `imageUploadURL` were not setup properly -- eg some folks didn't have them at all, or had them mismatched, or set the permissions too tightly. It's relateable considering that, AFAIK, we haven't have published specs for those folders... aside from CIVI-SA-2014-001...)

**Comment by JoeMurray** [comment]
@John-B thanks so much for all the work you are doing on documentation lately.

I think that WordPress plugin updates are safe enough, as 1/3 of the top million sites on the web do things that way. So allowing the web to write the extensions directory is safe enough. A comment in documentation could indicate that admins could make this safer and simultaneously less convenient by forcing manual downloads of all extensions and updates.

**Comment by John-B** [comment]
In my PR I have done what you suggest.

Off-topic, you say "I think that WordPress plugin updates are safe enough"... not my experience : have seen a few hacks where they got in by writing to the WordPress codebase with SQL injection. Also even more off topic, sometimes a hacker buys a plugin maintainership on the WP repo and injects malicious code upstream :-(( The joys of WordPress!

So personally I like to make my clients' php unwritable :-)

**Comment by mlutfy** [comment]
PR merged
