### ISSUE TITLE
Should we migrate install/upgrade docs for Drupal 6?

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-sysadmin-guide#4]
I would like some opinions from others on this one. 

Our downloads currently offer CiviCRM for Drupal 6: 

![image](https://user-images.githubusercontent.com/42411/30514706-91ddd51e-9ad7-11e7-8e70-8b0a89b0776c.png)

But the page on [installing for Drupal 6](https://wiki.civicrm.org/confluence/display/CRMDOC/Installing+CiviCRM+for+Drupal+6) has a big warning: 

![image](https://user-images.githubusercontent.com/42411/30514721-f3538de8-9ad7-11e7-9398-66433ac379d3.png)

I'm leaning towards migrating this content as-is (with the warning). Do other people have thoughts on whether maybe I should remove the warning or maybe I should just not even migrate these Drupal 6 pages?

**Comment by nganivet** [comment]
Background info, from the statistics:
- 50 active sites on Drupal6: 4.1 (10 sites), 4.2 (31), 4.5 (1 site), 4.6 (7 sites), 4.7 (1 site, our buildbot?)
- 10 active site with backdrop, all on recent version of 4.7

My vote is therefore for obsoleting CiviCRM on Drupal6:
- remove all download links to CiviCRM on Drupal 6 (for 4.7 AND 4.6 versions)
- keep the github repo as is, so people that REALLY want to install this still can
- either DO NOT migrate the Installing on Drupal 6 page (my preference), or if we migrate it let's migrate it to a buried deep-down Obsoleted / Unsupported section.

Do we officially support CiviCRM on Backdrop? If we do not yet, let's add (unsuported) at the end of the download link and move it to the end of the list. In any case, we must have an Installing on Backdrop page (if not already there).

**Comment by seamuslee001** [comment]
@nganivet my understanding is we are officially supporting Backdrop for 4.7 only see also [CRM-17711](https://issues.civicrm.org/jira/browse/CRM-17711)

If we are to obsolete it we need to give plenty of notice.  pinging @jackrabbithanna @guanhuan as the 4.6 maintainers

**Comment by nganivet** [comment]
@seamuslee001 To be crystal clear, I am proposing to obsolete Drupal 6 support for all CiviCRM versions. So this is not specific to 4.6 at all.

I so not think we should remove the code providing D6 support in CiviCRM from the 4.6 branch (on the fence about 4.7), but we should remove related documentation, don't build the tarballs anymore and do not offer a download link to any D6 versions of CiviCRM.

I do not think there is any announcement necessary since it officially has not been supported since 4.3 (4.5 years ago!), so by obsoleting we are just cleaning up things that should have been a long time ago.

**Comment by totten** [comment]
> 50 active sites on Drupal6: 4.1 (10 sites), 4.2 (31), 4.5 (1 site), 4.6 (7 sites), 4.7 (1 site, our buildbot?)

FWIW, we don't have a buildbot for D6.

It's a good point that the docs have redflagged D6 for a long time now.

If there were some hard+compelling need to change (eg if moving Civi to PHP 5.4/5.5 would break compatibility with D6), then we could potentially boot it, but I'd rather avoid anything heavy-handed, and I don't know a compelling need. Softer process seems preferable:

 * Wait until we have D8 supported. If someone gets booted from D6, then their rational move is migrating to D8 or Backdrop.
 * Make more announcements ahead of time -- eg in the blog and in-app.
 * On the download page, redflag the D6 tarball -- but still publish it.

**Comment by nganivet** [comment]
Just like to point out that we are only talking about 8 active sites here, and that this will not prohibit them from downloading CiviCRM updates if they want to, but just make it less convenient as they will not have a ready-made tarball.

**Comment by GinkgoFJG** [comment]
That's pretty inconvenient. I've been involved with CiviCRM for a long time, and I think I've rolled my own tarball a few times, but it would take me a while to remember how to do it and pull it off. Someone less familiar than me would probably need longer.

I second Tim that it's heavy-handed and unnecessary. I do have a couple D6 clients who are just now getting the funding, etc., that they need to migrate. Provided the load on the core team isn't unreasonable, I think there should be some overlap between D6 and D8 compatibility, since Drupal is recommending upgrading from 6 to 8, 7 to 9, etc.

Perhaps if/when the core team decides to prioritize an official D8 release they can make a simultaneous announcement that D6 support will be dropped 6 months after the first D8 release... or something like that.

**Comment by nganivet** [comment]
@GinkgoFJG wrote:
> make a simultaneous announcement that D6 support will be dropped 6 months after the first D8 release
Just to be clear, D6 support has been dropped with version 4.3 of CiviCRM, that is 4 and 1/2 ago!
Maybe @eileenmcnaughton should step in at this point in the discussion.

**Comment by eileenmcnaughton** [comment]
My position is that we should not do MORE work to either keep D6 going or to discontinue it. That basically means leave the tarball process as it is & don't migrate any documentation.

If at any time it becomes less work to drop D6 than to leave it as is then we should drop it - I feel we have signposted it long ago, as Nicolas pointed out..

**Comment by aydun** [comment]
The original question was about the docs for D6 rather than the broader topic of how and when to discontinue it.  If the existing D6 docs remain on the wiki there seems no benefit in migrating them to the new sysadmin guide.

**Comment by nganivet** [comment]
@eileenmcnaughton thanks for your insightful comment, agreed. So let's continue building the tarballs, but can we at least delete the links from the download page? Leaving them on such a public page sends IMO a wrong message about these being 'official' or even 'supported'. People that are still on D6 can then still download the latest tarballs from the saved URL (we are really talking about --one-- site using 4.7 on D6 ...)

**Comment by totten** [comment]
As Eileen said - the general idea is to maximize laziness wrt D6.

To @aydun's point and @seanmadsen's original question... don't bother migrating D6 instructions. That's extra work.

On the download page, keep the link but label it as `Download CiviCRM 4.7.24 for Drupal 6.x (deprecated)`. Changing the link is technically as much work as removing it, but removing the link is more likely to invite a philosophical thread (which would contradict the laziness directive).

**Comment by seanmadsen** [comment]
Thanks everyone. I think this has been a useful discussion. We seem to have a clear consensus on one point: don't migrate D6 docs. Ok cool. Less work for me! So I'm closing this ticket now with the conclusion that **I will not migrate the D6 installation and upgrade documentation to the Sysadmin Guide**. 

I think the can of worms I opened is healthy, but it's a bit beyond the scope of this ticket. I'm just trying to decide what to do about docs migration here. I fully support more discussion about the download links, but will refrain from offering an opinion here. I think that discussion should happen outside of this issue tracker, probably in [ops](http://lab.civicrm.org/infrastructure/ops/), or maybe in [civicrm-website](https://lab.civicrm.org/marketing-team/civicrm-website/issues).
