### ISSUE TITLE
Migrate lots of existing content into this guide

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-sysadmin-guide#5]
This is a placeholder issue for the large project of migrating content into this guide. 

* I'm managing the migration details in this [google spreadsheet](https://docs.google.com/spreadsheets/d/1kAuXQs6DatSj9Cr6q6DYquuEUNivK9_DvIztVZ_4_3c/edit#gid=0) (similar to the Dev Guide migration project).
    * Anyone can view, but you'll need to request access to edit. Please feel free to request access!
* The Dev Guide was mostly "one page at a time". With the Sysadmin Guide, I'm looking to do things a bit more "all at once" with a script to bring lots off stuff in and then manual cleaning thereafter. 
* I am running a [Make It Happen campaign](https://civicrm.org/make-it-happen/system-administrator-guide) to fund my time for this project.

**Comment by seanmadsen** [comment]
I'm pretty much done with my content import so I'm closing this ticket.

There's still some work to do though: 

* Content cleaning. I'm still working on this and also creating separate tickets for some cleaning tasks
* Wiki redirects (will go up soon, after some more of the cleaning is completed).

**Comment by colemanw** [comment]
Awesome work @seamuslee001 :1st_place_medal:
