### ISSUE TITLE
MySQL 5.1.6 - 5.7.6 permissions for installation

### ISSUE THREAD

**Issue by aksm** [civicrm/civicrm-sysadmin-guide#91]
Not sure if this is unique to my version of MySQL (5.7.22-0ubuntu0.16.04.1), but I needed the additional permission for REFERENCES when setting up the database, and it's not mentioned in the docs.

**Comment by MegaphoneJon** [comment]
This is correct, if no one handles this sooner I'll add this on the next documentation sprint.

**Comment by seamuslee001** [comment]
@aksm @MegaphoneJon looks like its already there as per https://docs.civicrm.org/sysadmin/en/latest/requirements/#mysql-576

**Comment by aksm** [comment]
@seamuslee001 It's there for 5.7.6+ but not for 5.1.6 - 5.7.6.

**Comment by MegaphoneJon** [comment]
There's a proposed fix at #136 but @aksm - your original comment here says you're running 5.7.22, so I'm confused about saying that `REFERENCES` is missing in the 5.1-5.7.6 docs.

**Comment by MikeyMJCO** [comment]
Resolved with #136
